### ISSUE TITLE
How to fix it

### ISSUE THREAD

**Issue by tellfa** [RajneeshSingh007/MusicX-Music-Player#5]
Hi, Thanks for this project
how can i fix error from below image
![51](https://user-images.githubusercontent.com/10583945/31043551-fa4e9de2-a5ca-11e7-92c4-74bb647cec8f.JPG)

**Comment by tellfa** [comment]
and please share it : E:/AndroidDevelopment/AppDevelopment/appDev/MusicX/app/proguard-rules.pro

**Comment by RajneeshSingh007** [comment]
@tellfa Hello,
you could remove that config or add your own key :wink:

**Comment by RajneeshSingh007** [comment]
@tellfa on github file is present..check once again😬
