### ISSUE TITLE
Reduce Delay Time

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [RajneeshSingh007/MusicX-Music-Player#6]
It takes delay time when first launch and after pressed back from Playing Views. How to reduce this time.
I use Galaxy J5 Prime.

thanks.

**Comment by RajneeshSingh007** [comment]
Thanks for feedback !! i'll work on it soon :)

**Comment by Thet-Tun-Aung** [comment]
Thank you very much . I expect it'll be better :-)
